<a href="https://colab.research.google.com/github/KrzMa/data-science/blob/main/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
print(dir(np))

## 1D Array

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y = np.array([1.2, 3.4, 5.9])
print(y)

[1.2 3.4 5.9]


In [ ]:
y.dtype

dtype('float64')

## 2D Array

In [ ]:
x = np.array([[1, 2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.shape

(2, 2)

In [ ]:
x.size

4

In [ ]:
y = np.array([[1, 2, 5],[9, 4, 5]])
print(y)

[[1 2 5]
 [9 4 5]]


In [ ]:
y.shape

(2, 3)

## 3D Array

In [ ]:
x = np.array(
    [[[4, 3, 1],
     [3, 4, 1]],

     [[4, 3, 10],
      [5, 8, 23]]]
    )
x

array([[[ 4,  3,  1],
        [ 3,  4,  1]],

       [[ 4,  3, 10],
        [ 5,  8, 23]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

## Typy danych

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.4, 2.3, 3.4])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1.4, 2.3, 3.4], dtype='int')
A.dtype

[1 2 3]


In [ ]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

## Tworzenie Tablic

In [ ]:
np.zeros(shape=(4, 10), dtype='int') # Domyślnie jest float

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Podstawowe operacje na tablicach

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A + B

array([6, 0, 7, 4])

In [ ]:
A - B

array([0, 2, 1, 0])

In [ ]:
A * B

array([ 9, -1, 12,  4])

In [ ]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
A * 2

array([6, 2, 8, 4])

In [ ]:
A + 3 * B

array([12, -2, 13,  8])

### Mnożenie macierzowe



In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
X * Y

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

## Generwowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
np.random.rand(10)

array([0.73926358, 0.03918779, 0.28280696, 0.12019656, 0.2961402 ,
       0.11872772, 0.31798318, 0.41426299, 0.0641475 , 0.69247212])

In [ ]:
np.random.rand(10, 3)

array([[0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 ],
       [0.31856895, 0.66741038, 0.13179786],
       [0.7163272 , 0.28940609, 0.18319136],
       [0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797],
       [0.73519402, 0.96218855, 0.24875314],
       [0.57615733, 0.59204193, 0.57225191],
       [0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695]])

In [ ]:
np.random.randint(10)

8

In [ ]:
np.random.randint(low=10, high=50)

26

In [ ]:
np.random.randint(low=10, high=100, size=10)

array([34, 39, 31, 35, 90, 70, 71, 93, 43, 42])

In [ ]:
np.random.choice([4, 2, 1, 9, 0, 2, 3])

0

In [3]:
np.random.choice(['python', 'java', 'sql'])

'sql'

In [4]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x = np.random.shuffle(data)

In [9]:
print(data)

[7 2 0 4 8 6 3 5 9 1]


## Podstawowe funkcje numpy

In [10]:
np.exp(1)

2.718281828459045

In [11]:
np.sqrt(225)

15.0

In [12]:
np.all([2, 3, 1])

True

In [14]:
np.all([1, 0, 2])

False

In [15]:
np.any([1, 2, 3, 4, 0])

True

In [16]:
np.any([0, 0, 0, 0])

False

In [23]:
A = np.random.randn(5)
A

array([ 1.11107995,  0.55509881,  0.86473213, -0.74760757,  0.39928388])

In [19]:
np.argmax(A)

4

In [20]:
A[np.argmax(A)]

0.3034448080062121

In [21]:
A[np.argmin(A)]

-1.840866667562073

In [24]:
np.argsort(A)

array([3, 4, 1, 2, 0])

In [25]:
np.max(A)

1.111079952118235

In [26]:
np.min(A)

-0.7476075678982735

In [27]:
np.mean(A)

0.43651743866422416

In [28]:
np.median(A)

0.5550988062802591

In [29]:
np.std(A)

0.6412491422702986

## Indeksowanie, wycinanie

In [48]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
A[2]

2

In [33]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [34]:
A[:2]

array([0, 1])

In [35]:
A[10:15]

array([10, 11, 12, 13, 14])

In [50]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
A[:, 0]

array([ 0,  5, 10, 15])

In [42]:
A[1, 1]

6

In [44]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [45]:
A[1, 4] = 3
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  3],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Iteracja po tablicach

In [46]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  3],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [53]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


## Zmiana rozmiaru tablic

In [54]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
A.shape

(4, 5)

In [57]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [59]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

## Maski logiczne

In [61]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [62]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
# A[A > 0]

In [65]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [66]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [67]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])